name: Docker Image CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Matrix
      id: set-matrix
      run: |
        DOCKERFILES=$(ls ${{ github.workspace }}/build/*.Dockerfile | jq -R -s -c 'split("\n")[:-1]')
        echo "::set-output name=matrix::{\"dockerfile\":${DOCKERFILES}}"

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run build job for ${{ matrix.dockerfile }}
      run: |
        docker build --tag "openspace-${{ matrix.dockerfile.Dockerfile }}" --file "${{ matrix.dockerfile }}" .