name: Docker Image CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - id: set-matrix
      run: |
        DOCKERFILES=$(ls ${{ github.workspace }}/build/*.Dockerfile | xargs -n 1 basename)
        echo "::set-output name=matrix::{\"dockerfile\": [\"$DOCKERFILES\"]}"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      working-directory: ${{ github.workspace }}/build
      run: |
        echo "Building ${{ matrix.dockerfile }}"
        docker build --tag "openspace-${{ matrix.dockerfile%.Dockerfile }}" --file "${{ matrix.dockerfile }}" .